import Head from 'next/head'
import { Inter } from 'next/font/google'
import Image from 'next/image';
import Banner from '../assets/banner.png'
import styles from '@/styles/Home.module.css'

import Categorias from '@/components/Categorias/Categorias';
import CampoDeBusca from '@/components/CampoDeBusca/CampoDeBusca';
import Cards from '@/components/Cards/Cards';

import { filtrarProdutos, buscarProdutos, produtosEntradas } from '@/service';
import { useState } from 'react';
import { produtos } from '@/data/data-produtos';
import imagemTeste from '@/assets/img/agua.jpg'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [dadosFiltrados, setDadosFiltrados] = useState(produtosEntradas);
  const [textoBuscaDigitada,  setTextoBuscaDigitada] = useState();

  const [botaoClicado, setBotaoClicado] = useState("Entradas");

  function handleBusca(textoDigitado){
    setTextoBuscaDigitada(textoDigitado);
    setDadosFiltrados(buscarProdutos(textoDigitado));
    setBotaoClicado("")
  }
  
  function handleFiltro(categoria){
    setTextoBuscaDigitada("");
    setDadosFiltrados(filtrarProdutos(categoria));
    setBotaoClicado(categoria);
  }

  return (
    <>
      <Head>
        <title>Cardapio de restaurante</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.banner}>
        <Image src={Banner} alt='banner'/>
        <div className={styles.container}>
          <h1>restaurante</h1>

          <p>
            De pratos clássicos a criações surpreendentes, nosso cardápio é um requinte de sabores refinados
          </p>
        </div>
      </header>

      <body>
        <Categorias 
          handleFiltro={handleFiltro}
        />

        <CampoDeBusca 
          textoBuscaDigitada={textoBuscaDigitada}
          handleBusca={handleBusca}
        />
        
        <section className={styles.sessaoCardapio}>
          <h3>Cardápio</h3>

          <section className={styles.sessaoCardapio_Cards}>
            {dadosFiltrados.map((produto) => {
              return(
                <>
                <Cards 
                  key={produto.id} 
                  imagem ={produto.imagem}  
                  nome={produto.nome}  
                  categoria={produto.categoria}
                  descricao={produto.descricao}
                  valor={produto.preco}
                  />
                  
                </>
              )
            })

            }

           

          </section>
        </section>
        
      </body>
      
            

            
    </>
  )
}
