import Head from 'next/head'
import { Inter } from 'next/font/google'
import Image from 'next/image';
import Banner from '../assets/banner.png'
import styles from '@/styles/Home.module.css'

import Categorias from '@/components/Categorias/Categorias';
import CampoDeBusca from '@/components/CampoDeBusca/CampoDeBusca';
import Cards from '@/components/Cards/Cards';

import { filtrarProdutos, buscarProdutos, produtosEntradas } from '@/service';
import { useState } from 'react';
import { produtos } from '@/data/data-produtos';
import imagemTeste from '@/assets/img/agua.jpg'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  // const [dadosFiltrados, setdadosFiltrados] = useState(produtosEntradas);
  // const [textoBuscaDigitada,  ]

  return (
    <>
      <Head>
        <title>Cardapio de restaurante</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.banner}>
        <Image src={Banner} alt='banner'/>
        <div className={styles.container}>
          <h1>restaurante</h1>

          <p>
            De pratos clássicos a criações surpreendentes, nosso cardápio é um requinte de sabores refinados
          </p>
        </div>
      </header>

      <body>
        <Categorias />
        <CampoDeBusca />
        
        <section className={styles.sessaoCardapio}>
          <h3>Cardápio</h3>

          <section className={styles.sessaoCardapio_Cards}>
            {/* {produtos.map((produto) => {
              return(
                <>
                <Cards key={produto.id} imagem ={produto.imagem}  nome={produto.nome}  descricao={produto.descricao}/>
                </>
              )
            })

            } */}

            <Cards imagem={imagemTeste} nome='lele' categoria='bebida' descricao='lorem11111111111111111111111111111111111111111' valor='21,99'/>
            

            <Cards imagem={imagemTeste} nome='lele' categoria='bebida' descricao='lorem11111111111111111111111111111111111111111' valor='21,99'/>
            <Cards imagem={imagemTeste} nome='lele' categoria='bebida' descricao='lorem11111111111111111111111111111111111111111' valor='21,99'/>

            <Cards imagem={imagemTeste} nome='lele' categoria='bebida' descricao='lorem11111111111111111111111111111111111111111' valor='21,99'/>
            <Cards imagem={imagemTeste} nome='lele' categoria='bebida' descricao='lorem11111111111111111111111111111111111111111' valor='21,99'/>

          </section>
        </section>
        
      </body>
      
            

            
    </>
  )
}
