import Head from 'next/head'
import { Inter } from 'next/font/google'
import Image from 'next/image';
import Banner from '../assets/banner.png'
import styles from '@/styles/Home.module.css'

import Categorias from '@/components/Categorias/Categorias';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Cardapio de restaurante</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.banner}>
        <Image src={Banner} alt='banner'/>
        <div className={styles.container}>
          <h1>restaurante</h1>

          <p>
            De pratos clássicos a criações surpreendentes, nosso cardápio é um requinte de sabores refinados
          </p>
        </div>
      </header>

      <body>
        <Categorias />
      </body>
      
            

            
    </>
  )
}
